---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-audiobooks-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "audiobookshelf.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.audiobooks.storage }}
  storageClassName: {{ .Values.persistence.storageClass }}
