---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.karakeep.name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  NEXTAUTH_SECRET: {{ .Values.NEXTAUTH_SECRET | b64enc }}
  MEILI_MASTER_KEY: {{ .Values.MEILI_MASTER_KEY | b64enc }}
  NEXT_PUBLIC_SECRET: {{ .Values.NEXT_PUBLIC_SECRET | b64enc }}
