---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.meilisearch.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.meilisearch.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.meilisearch.service.port }}
      targetPort: {{ .Values.meilisearch.service.targetPort }}
  type: {{ .Values.meilisearch.service.type }}
