---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.meilisearch.name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.meilisearch.persistence.storage }}
  storageClassName: {{ .Values.meilisearch.persistence.storageClassName }}
