---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-event-exporter.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-event-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    logLevel: {{ .Values.config.logLevel }}
    logFormat: {{ .Values.config.logFormat }}
    metricsNamePrefix: {{ .Values.config.metricsNamePrefix }}
    route:
      {{- toYaml .Values.config.route | nindent 6 }}
    receivers:
      {{- toYaml .Values.config.receivers | nindent 6 }}
