
repos:
  - repo: local
    hooks:
      - id: just-check
        name: Run checks on repo
        entry: just check
        language: system
        pass_filenames: false
        always_run: true

      - id: run-repomix
        name: Generate Repomix Context for Claude
        entry: repomix
        language: system
        pass_filenames: false
        always_run: true
