---
apiVersion: v2
name: forgejo
description: A Helm chart to deploy Forgejo git service
type: application
version: 0.1.0
appVersion: "14.0.1"

dependencies:
  - name: forgejo
    version: "16.2.1"
    repository: "oci://code.forgejo.org/forgejo-helm"
  - name: homelab-common
    version: 0.1.0
    repository: "file://../homelab-common"
