---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "open-terminal.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "open-terminal.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
