---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: open-webui-vss
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: {{ .Values.vault.secretPath }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vault.secretName }}
    overwrite: true
