# roles/common/tasks/main.yaml

- name: Update and upgrade all pacman packages
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  tags:
    - upgrade
    - never

- name: Install essential system packages
  community.general.pacman:
    name:
      - base-devel
      - git
      - curl
      - wget
      - vim
      - sudo
      - yay  # AUR helper, installed via AUR in a later step
      - openssh
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/10-wheel-passwordless
    state: present
    create: yes
    validate: 'visudo -cf %s'
    line: '%wheel ALL=(ALL:ALL) NOPASSWD: ALL'
    mode: '0440'

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
