---
apiVersion: v2
name: jellyfin
description: A Helm chart for Jellyfin media server
type: application
version: 0.1.0
appVersion: "10.11.5"
dependencies:
  - name: homelab-common
    version: 0.1.0
    repository: "file://../homelab-common"
