---
replicaCount: 1
namespace: media
name: jellyfin

image:
  repository: jellyfin/jellyfin
  pullPolicy: IfNotPresent
  tag: "10.11.5"

service:
  type: ClusterIP
  port: 8096

ingress:
  enabled: true
  className: "traefik"
  host: jellyfin.homelab.local
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca
  tls:
    - secretName: jellyfin-tls
      hosts:
        - jellyfin.homelab.local

tailscale:
  enabled: true
  serviceName: jellyfin

persistence:
  storageClass: local-path
  config:
    storage: 5Gi
  media:
    movies:
      hostPath: /home/celsuss/Videos/movies
    tvshows:
      hostPath: "/home/celsuss/Videos/tv shows"

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 4Gi

plugins:
  enabled: true
  overwriteRepositories: false
  repositories:
    - name: "Intro Skipper"
      url: "https://intro-skipper.org/manifest.json"
      enabled: true
    - name: "Jellyfin Enhanced"
      url: "https://raw.githubusercontent.com/n00bcodr/Jellyfin-Enhanced/main/manifest.json"
      enabled: true
    - name: "Skin Manager"
      url: "https://raw.githubusercontent.com/danieladov/JellyfinPluginManifest/master/manifest.json"
      enabled: true
