{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wyoming-piper.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wyoming-piper.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
