version: '3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" #This is required if you enable DHCP server on PiHole
      - "80:80/tcp"
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    environment:
      TZ: 'Europe/Stockholm'
      # WEBPASSWORD: 'very secure password'

     #Recommended but not required (DHCP needs NET_ADMIN)
    cap_add:
      - NET_ADMIN
