---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "donetick.fullname" . }}-config-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.configStorage }}
  storageClassName: {{ .Values.persistence.storageClassName }}
