---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "donetick.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "donetick.labels" . | nindent 4 }}
type: Opaque
data:
  jwtSecret: {{ .Values.jwt.secret | b64enc }}
