---
# https://gitea.com/gitea/helm-gitea/src/branch/main/values.yaml
gitea:
  valkey-cluster:
    enabled: false
  valkey:
    enabled: true
  postgresql:
    enabled: true
  postgresql-ha:
    enabled: false

  persistence:
    enabled: true

  gitea:
    config:
      database:
        DB_TYPE: postgres
      indexer:
        ISSUE_INDEXER_TYPE: bleve
        REPO_INDEXER_ENABLED: true
    # additionalConfigSources:
    #   - secret:
    #       secretName: gitea-app-ini-oauth
    #   - configMap:
    #       name: gitea-app-ini-plaintext
