---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "khoj.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "khoj.labels" . | nindent 4 }}
data:
  # -- Internal service dependencies are dynamically constructed
  POSTGRES_HOST: "{{ include "khoj.fullname" . }}-database"
  POSTGRES_PORT: "{{.Values.database.service.port }}"
  KHOJ_SEARXNG_URL: "http://{{ include "khoj.fullname" . }}-search:{{.Values.search.service.port }}"
  KHOJ_TERRARIUM_URL: "http://{{ include "khoj.fullname" . }}-sandbox:{{.Values.sandbox.service.port }}"

  # -- Application configuration from values.yaml
  KHOJ_ADMIN_EMAIL: {{.Values.khoj.config.adminEmail | quote }}
  KHOJ_DEBUG: {{.Values.khoj.config.debug | quote }}
  # Use 'default' to prevent errors if the value is not in values.yaml
  KHOJ_TELEMETRY_ENABLED: {{ (not (default false .Values.khoj.config.disableTelemetry)) | quote }}

  # -- Connection to external Ollama service
  OPENAI_BASE_URL: {{.Values.khoj.config.ollamaUrl | quote }}
