---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "khoj.fullname" . }}-database
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "khoj.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  serviceName: {{ include "khoj.fullname" . }}-database
  replicas: 1
  selector:
    matchLabels:
      {{- include "khoj.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "khoj.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      {{- with.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: database
          image: "{{.Values.database.image.repository }}:{{.Values.database.image.tag }}"
          imagePullPolicy: {{.Values.imagePullPolicy }}
          ports:
            - name: postgres
              containerPort: {{.Values.database.service.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{.Values.secrets.existingName }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          {{- with.Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  {{- if.Values.database.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [{{.Values.database.persistence.accessMode }}]
        {{- if.Values.database.persistence.storageClass }}
        storageClassName: {{.Values.database.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{.Values.database.persistence.size }}
  {{- end }}
