---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "khoj.fullname" . }}-database
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "khoj.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None # This makes the service "headless"
  ports:
    - port: {{.Values.database.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "khoj.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
