---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "khoj.fullname" . }}-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "khoj.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{.Values.khoj.service.type }}
  ports:
    - port: {{.Values.khoj.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "khoj.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
