---
{{- if.Values.khoj.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "khoj.fullname" . }}-config-pvc
  labels:
    {{- include "khoj.labels" . | nindent 4 }}
    app.kubernetes.io/component: server-config
spec:
  accessModes:
    - {{.Values.khoj.persistence.config.accessMode }}
  resources:
    requests:
      storage: {{.Values.khoj.persistence.config.size }}
  {{- if.Values.khoj.persistence.config.storageClass }}
  storageClassName: {{.Values.khoj.persistence.config.storageClass }}
  {{- end }}
{{- end }}
