---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "khoj.fullname" . }}-sandbox
  labels:
    {{- include "khoj.labels" . | nindent 4 }}
    app.kubernetes.io/component: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "khoj.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sandbox
  template:
    metadata:
      labels:
        {{- include "khoj.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sandbox
    spec:
      {{- with.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: sandbox
          image: "{{.Values.sandbox.image.repository }}:{{.Values.sandbox.image.tag }}"
          imagePullPolicy: {{.Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.sandbox.service.port }}
              protocol: TCP
          {{- with.Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
