---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "khoj.fullname" . }}-search
  labels:
    {{- include "khoj.labels" . | nindent 4 }}
    app.kubernetes.io/component: search
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "khoj.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: search
  template:
    metadata:
      labels:
        {{- include "khoj.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: search
    spec:
      {{- with.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: search
          image: "{{.Values.search.image.repository }}:{{.Values.search.image.tag }}"
          imagePullPolicy: {{.Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.search.service.port }}
              protocol: TCP
          {{- with.Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
