---
# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: khoj-secrets # This must match values.yaml secrets.existingName
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  # -- Credentials for the PostgreSQL database
  POSTGRES_USER: "khoj_user"
  POSTGRES_PASSWORD: {{ .Values.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_DB: "khoj_db"
  # -- Credentials for the Khoj application
  KHOJ_ADMIN_PASSWORD: {{ .Values.KHOJ_ADMIN_PASSWORD | b64enc }}
  KHOJ_DJANGO_SECRET_KEY: {{ .Values.KHOJ_DJANGO_SECRET_KEY | b64enc }}
