---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "khoj.fullname" . }}-vss
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "khoj.labels" . | nindent 4 }}
spec:
  vaultAuthRef: khoj-vault-auth
  mount: secret
  type: kv-v2
  path: {{ .Values.vault.secretPath }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vault.secretName }}
    overwrite: true
