---
# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

vault:
  secretPath: argocd/oidc
  secretName: argocd-oidc-secret

argo-cd:
  global:
    image:
      # repository: ghcr.io/celsuss/argo-cd-repo-server-sops
      # tag: "1.0.10"
      repository: quay.io/argoproj/argocd
      tag: "v3.1.4"
      pullPolicy: IfNotPresent

    domain: argocd.homelab.local

    logging:
      # -- Set the global logging format. Either: `text` or `json`
      format: text
      # -- Set the global logging level. One of: `debug`, `info`, `warn` or `error`
      level: info

  dex:
    enabled: false

  configs:
    params:
      server.insecure: "true"

    cm:
      url: https://argocd.homelab.local
      oidc.config: |
        name: Kanidm
        issuer: https://kanidm.homelab.local/oauth2/openid/argocd
        clientID: argocd
        clientSecret: $argocd-oidc-secret:client-secret
        requestedScopes:
          - openid
          - profile
          - email
          - groups

    tls:
      certificates:
        kanidm.homelab.local: |
          -----BEGIN CERTIFICATE-----
          MIIE9zCCAt+gAwIBAgIRAM6zEn3WF6ihBjl3hwMedyQwDQYJKoZIhvcNAQENBQAw
          FTETMBEGA1UEAxMKaG9tZWxhYi1jYTAeFw0yNjAzMTMxMzAxMTFaFw0zNjAzMTAx
          MzAxMTFaMBUxEzARBgNVBAMTCmhvbWVsYWItY2EwggIiMA0GCSqGSIb3DQEBAQUA
          A4ICDwAwggIKAoICAQDiSgLdoI3SoLB/577Cf8Ub6I7hAC02wJ4iDdw2ZtT9RZqP
          C8Ne+9XZ/VE4+hPeqso1DCQ60p3VODTqEYy9bYHFER3dbJOFzPcEkmsZ80gSfdWJ
          qOH6Rs4eWwgqyH30+XvtGNDu9sKZPeYZmr9OaOuiagn7DbUgSDqqd2o/xlOCZCTO
          06UI4t5DcyiHcYvD/HMUmiuNPkIlbu6n29ayn3SNAF+erY11kV9DpgJxe8upxvvO
          wjhgBAgIidKU3pXYHOZv/RetJEnqSULoTzo5hHn644B5P4HnO/TJoaOrQxN25JGe
          0XyILM/1Y8ntA2xFKv8c6rEtwDBFYpUNki+Yukjw0iWooR3ZV9FR2sn9R1icfDRQ
          ikoHeiIk5OwbMP/Uniem3jOuk0PiMBdQqb4BElYxqeg41CwRpyMwEwzsQciHvf3A
          q1YZotq3kgcagtEf2M798T8GsYr2vJIAft7OQs1vhJGjxmkrVOPR96ThY2uc+6yf
          iMj2xvqCKyKOt1pgEwMePES2ROdLEgEqxdvc0+R42i2o0E3WNEWboS9ZIEHrFjqd
          pzWX+oZsuVerTpP0W8PKnP/9NwWRtdmiTQjbBiAn9MHcoPnF8ZZobxvmxwPL02s1
          /3ElSWPksgO4YAuhrhovyIC5OQF6uaJb/6b4Cs3D5n57ep/Z1hvZQ+adPjyFwwID
          AQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4E
          FgQUz3udA7TDTN8A+1lrigmI6KaTOSUwDQYJKoZIhvcNAQENBQADggIBAIVWn5n6
          MaCVWdBbgZ///bfDrIm3BCHQ5x8pxzXjcMyHzAykdRQ4efJC99TDg102nDNhCxZO
          uv86jlBr3Ckt5izhg4m9dqijP6OmypWXcVtzFKxwlV4fWXyzOsmrNVUyHxLKun6l
          WdHuRUn+OO8U7OdbyKFeju3CmfPLWlAsGoaBbo9Mw7xwCw3QvbOvQNvKb3EPufh9
          ZEAzBH1nV5MCKWdKfO3JWPr4jMOy172hswpBURlK1RrpMhcMAhXX0qRdtywbZF99
          0thPGEiOGB1d7aulXUzyRxMo5Sw+hOgErLvS4Q//c6InlDmwa6cuohl2ztoJNX2z
          QzB8Mc2DmDgJj+CSMsW+XqumdZh4iIFA+enLq3RIxlWv/rAC0EiVGHa2OOo3qmOx
          gw+G9M+n9vLWR6b+lUilx0QHi/uosSBMwDe2+T0RG5oN+gRSBPBYlSQfsMhFAJv6
          Ged/sWEC1CIlhrhKtV4ikXgUk7aiFUesz1ye1DrXaC6yqQW0vg/JvQTfrWG9XOX7
          Cx/gcA5etAEou4zqnxU5Ulq7WeETKR4fXJHnL7o6D3QOqJnGTfa5sCnC3BXWTJuE
          SUsrv5P83E+WwF21U8n/5cjrHLWi2lO7g1eWj7v5f02NdbOX58Ii7Ly0R5HxZfP1
          qQ8n5Lai9T1lIGrjd6UxeUWDGN9AKDkYRcrD
          -----END CERTIFICATE-----

    rbac:
      policy.csv: |
        g, sso_users, role:admin
      policy.default: role:readonly

  server:
    replicas: 1
    extraArgs:
      - --insecure
      - --repo-server-timeout-seconds=240

    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: argocd.homelab.local
      servicePortName: http
      annotations:
        traefik.ingress.kubernetes.io/service.scheme: h2c
        cert-manager.io/cluster-issuer: homelab-ca
      tls: true

    resources:
      requests:
        cpu: 50m
        memory: 128Mi

  repoServer:
    replicas: 1
    # -- Use the custom image that includes the sops binary.
    image:

      # repository: ghcr.io/celsuss/argo-cd-repo-server-sops
      # tag: "1.0.12" # "1.0.10"

      repository: quay.io/argoproj/argocd
      tag: "v3.1.4"
      pullPolicy: IfNotPresent


    # env:
    #   - name: HELM_PLUGINS
    #     value: /home/argocd/.local/share/helm/plugins
    #   - name: HELM_SECRETS_QUIET
    #     value: "true"

    volumes:
      - name: sops-age-key
        secret:
          secretName: sops-age-key
          defaultMode: 0400
    volumeMounts:
      - name: sops-age-key
        mountPath: /home/argocd/.config/sops/age/
        readOnly: true
    resources:
      requests:
        cpu: 50m
        memory: 128Mi

  controller:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  applicationSet:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
  redis:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
