---
replicaCount: 1
name: ezbookkeeping
namespace: finance

image:
  repository: mayswind/ezbookkeeping
  pullPolicy: IfNotPresent
  tag: "0.10"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

env:
  - name: EBK_SERVER_DOMAIN
    value: ezbookkeeping.homelab.local

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "traefik"
  host: ezbookkeeping.homelab.local
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca
  tls:
    - secretName: ezbookkeeping-tls
      hosts:
        - ezbookkeeping.homelab.local

persistence:
  storageClass: local-path
  storage: 3Gi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

tailscale:
  enabled: false
  serviceName: ezbookkeeping
