---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: glance-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "glance.labels" . | nindent 4 }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: homelab/glance
  refreshAfter: 60s
  destination:
    create: true
    name: glance-secrets
    overwrite: true
