---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: machine-learning
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ml.persistence.modelCache.size }}
  storageClassName: {{ .Values.ml.persistence.modelCache.storageClass }}
