---
apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "immich.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
