---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-valkey-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.valkey.persistence.size }}
  storageClassName: {{ .Values.valkey.persistence.storageClass }}
