version: '3.9'
services: 
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock