---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: ezbookkeeping
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/Celsuss/Home-Lab.git
#     path: helm/charts/ezbookkeeping
#     targetRevision: HEAD
#     helm:
#       valueFiles:
#         - values.yaml
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: finance
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
