---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Celsuss/Home-Lab.git
    path: helm/charts/karakeep
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-secrets.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
