---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Celsuss/Home-Lab.git
    path: helm/charts/ollama
    targetRevision: HEAD
    # helm:
    #   valueFiles:
    #     - values.yaml
    #   parameters:
    #     - name: image.tag
    #       value: "latest"
    #     - name: gpu.enabled
    #       value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-workloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
