---
namespace: karakeep

karakeep:
  replicaCount: 1
  name: karakeep

  image:
    repository: ghcr.io/karakeep-app/karakeep
    pullPolicy: IfNotPresent
    tag: ""

  env:
    - name: DATA_DIR
      value: /data
    - name: MEILI_ADDR
      value: http://meilisearch:7700
      # value: "http://{{ .Release.Name }}-meilisearch:7700"
    - name: BROWSER_WEB_URL
      value: http://chrome:9222
      # value: http://{{ .Release.Name }}-chrome:9222
    - name: NEXTAUTH_URL
      value: http://karakeep.homelab.local
      # value: http://localhost:3000
      # value: "{{ .Values.applicationProtocol }}://{{ .Values.applicationHost }}"
    - name: KARAKEEP_VERSION
      value: "release"
    # Add OPENAI_API_KEY to the ConfigMap if necessary

  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000


  persistence:
    storageClassName: "local-path"
    storage: 1Gi

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "500m"

meilisearch:
  replicaCount: 1
  name: meilisearch

  image:
    repository: getmeili/meilisearch
    pullPolicy: IfNotPresent
    tag: "v1.11.1"

  env:
    - name: MEILI_NO_ANALYTICS
      value: "true"

  service:
    port: 7700
    targetPort: 7700
    type: ClusterIP

  persistence:
    storageClassName: "local-path"
    storage: 1Gi

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

chrome:
  replicaCount: 1
  name: chrome

  image:
    repository: gcr.io/zenika-hub/alpine-chrome
    pullPolicy: IfNotPresent
    tag: "123"

  command:
    - chromium-browser
    - --headless
    - --no-sandbox
    - --disable-gpu
    - --disable-dev-shm-usage
    - --remote-debugging-address=0.0.0.0
    - --remote-debugging-port=9222
    - --hide-scrollbars

  service:
    type: ClusterIP
    port: 9222
    targetPort: 9222

  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1000m"


ingress:
  enabled: true
  className: traefik
