---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tandoor-recipes.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tandoor-recipes.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tandoor-recipes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tandoor-recipes.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "tandoor-recipes.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              value: {{ include "tandoor-recipes.fullname" . }}-db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: ALLOWED_HOSTS
              value: "*"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vault.secretName }}
                  key: SECRET_KEY
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vault.secretName }}
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: media
              mountPath: /opt/recipes/mediafiles
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "tandoor-recipes.fullname" . }}-media
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
