---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tandoor-recipes.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tandoor-recipes.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.storage }}
