---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tandoor-recipes.fullname" . }}-db
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tandoor-recipes.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: {{ include "tandoor-recipes.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
