{{- if .Values.hass.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "wyoming-whisper.fullname" . }}-vss
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wyoming-whisper.labels" . | nindent 4 }}
spec:
  vaultAuthRef: wyoming-whisper-vault-auth
  mount: secret
  type: kv-v2
  path: {{ .Values.vault.secretPath }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vault.secretName }}
    overwrite: true
{{- end }}
