---
{{- if.Values.subnetRouter.enabled }}
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: {{ include "tailscale.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tailscale.labels" . | nindent 4 }}
spec:
  hostname: {{ .Values.subnetRouter.hostname | quote }}
  subnetRouter:
    advertiseRoutes:
      {{- toYaml .Values.subnetRouter.routes | nindent 6 }}
{{- end }}
