---
{{- if.Values.tailscale-operator.oauth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.oauthSecret.name }}
  namespace: {{.Release.Namespace }}
  labels:
    {{- include "k3s-tailscale-gateway.labels". | nindent 4 }}
type: Opaque
stringData:
  # IMPORTANT: The operator expects the keys to be 'client_id' and 'client_secret'.
  # This is a subtle but critical detail if you are pre-creating the secret.
  client_id: {{.Values.tailscale-operator.oauth.clientId | quote }}
  client_secret: {{.Values.tailscale-operator.oauth.clientSecret | quote }}
{{- end }}
