---
{{- if.Values.oauthSecret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oauthSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # IMPORTANT: The operator expects the keys to be 'client_id' and 'client_secret'.
  # This is a subtle but critical detail if you are pre-creating the secret.
  client_id: {{ .Values.oauth.clientId | quote }}
  client_secret: {{ .Values.oauth.clientSecret | quote }}
{{- end }}
