# .github/workflows/docker-build-and-push.yml

name: Build and Push Changed Docker Images
on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'

jobs:
  identify-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_apps: ${{ steps.changes.outputs.changes }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Identify Changed Applications
        id: changes
        uses: dorny/paths-filter@v3.0.2
        with:
          list-files: none
          filters: |
            argo-cd-repo-server-sops:
              - 'docker/argo-cd-repo-server-sops/**'

  build-and-push:
    needs: identify-changes
    if: needs.identify-changes.outputs.changed_apps != ''
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJSON(needs.identify-changes.outputs.changed_apps) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Convert name to lowercase or else docker push won't work
      - name: Convert owner name to lowercase
        id: string
        run: |
          echo "owner_lc=${{ github.repository_owner,,}}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./docker/${{ matrix.app }}
          push: true
          tags: ghcr.io/${{ steps.string.outputs.owner_lc }}/${{ matrix.app }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Print Pushed Image Path
        run: |
          # ✅ This line is also modified to use the new lowercase variable
          echo "✅ Successfully built and pushed image: ghcr.io/${{ steps.string.outputs.owner_lc }}/${{ matrix.app }}:latest"
